from pathlib import Path
from html import escape as esc
import json,re
ROOT=Path(__file__).resolve().parents[1]
NAV=[('index','Home'),('organizations','Organizations'),('experience','Get Experience'),('skills','Skills'),('careers','Careers'),('vehicle-dynamics','Vehicle Dynamics'),('projects','Projects'),('resources','Resources'),('books','Books')]
def link(url,label):return f'<a href="{esc(url,quote=True)}" target="_blank" rel="noopener noreferrer">{esc(label)} <span aria-hidden="true">↗</span></a>'
def links(items):return '<div class="links">'+''.join(link(u,t) for t,u in items)+'</div>'
def head(kicker,title,desc):return f'<header class="pagehead"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{desc}</p></header>'
def section(num,title,body,intro=''):return f'<section class="section"><div class="section-title"><span class="section-num">{num}</span><h2>{title}</h2></div>'+ (f'<p class="section-intro">{intro}</p>' if intro else '')+body+'</section>'
def card(title,body,urls=[],tag=''):return '<article class="card">'+(f'<span class="pill">{tag}</span>' if tag else '')+f'<h3>{title}</h3><p>{body}</p>'+links(urls)+'</article>'
def grid(items):return '<div class="grid">'+''.join(items)+'</div>'
def slot(id,label):return f'<div class="upload-slot" data-image-slot><img alt="Preview of {label}"><label for="{id}">{label}</label><input id="{id}" type="file" accept="image/png,image/jpeg,image/webp"><small role="status">Local preview only. Publishing an image requires adding it to the site project.</small></div>'
def write(page,title,body,desc='Practical motorsports resources, student racing organizations, vehicle dynamics, and career guidance from Tatum Langston.'):
 nav=''.join(f'<a href="{p}.html"'+(' aria-current="page"' if p==page else '')+f'>{t}</a>' for p,t in NAV)
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{esc(desc,quote=True)}"><meta name="theme-color" content="#101925"><title>{title} | Tatum Langston</title><link rel="stylesheet" href="styles.css"><script src="site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="topbar"><nav class="nav" aria-label="Main navigation">{nav}</nav></header><main id="main">{body}</main><footer class="footer"><span>Tatum Langston · Motorsports resources</span><span><a href="resources.html">Resources</a> · <a href="books.html">Reading list</a> · <a href="#main">Back to top</a></span></footer></body></html>'''
 (ROOT/f'{page}.html').write_text(html)

home='''<section class="hero"><div><div class="checkered" aria-hidden="true"></div><p class="eyebrow">A practical starting point in motorsports</p><h1>Tatum<br>Langston</h1><p class="role">NASCAR CUP SERIES PERFORMANCE ENGINEER</p><p class="intro">I'm a Purdue University graduate in Mechanical Engineering Technology and a NASCAR Cup Series Performance Engineer at Spire Motorsports, supporting all three cars before moving into a NASCAR Cup Series Race Engineer role in 2027.</p><p>My background includes R&amp;D with Andretti Global’s IndyCar program, design engineering at Utilimaster, and student racing with Windsor Racing, Lady Elizabeth EV, and ShreveHart Racing.</p><p>My time in student racing led to some of my proudest achievements: becoming the first woman to win an EV Grand Prix, founding and leading the first all-women team to win a Purdue Grand Prix, and setting the Purdue Grand Prix women’s track record. Beyond the track, I competed in the first annual Women with Drive case competition.</p><p>Created for the American Speed Festival at <a href="https://m1concourse.com/" target="_blank" rel="noopener noreferrer">M1 Concourse</a>, this hub shares practical ways to get involved in racing, build skills, and explore motorsports careers.</p><div class="links"><a class="button" href="resources.html">Explore the resources</a><a href="experience.html">Find a way to get involved</a></div><div class="contact-links"><a href="mailto:tatumlang951@gmail.com">tatumlang951@gmail.com</a><a href="https://www.linkedin.com/in/t-langston" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></div><figure class="hero-photo"><img src="assets/tatum-graduation.jpg" alt="Tatum Langston at Purdue graduation, holding a checkered flag" width="1365" height="2048" fetchpriority="high"></figure></section><section class="home-note"><div><h2>There isn't one route into racing.</h2><p>Student teams, local racing, manufacturing, data analysis, internships, and volunteering can all be useful places to start. Pick an opportunity you can take part in consistently, ask questions, and document what you learn.</p><p class="m1-intro">M1 Concourse is a great place to connect with the motorsports community. Its automotive festivals, events, and driving experiences offer ways to meet fellow enthusiasts, see cars on track, and find inspiration for your own path into racing.</p><div class="links"><a href="https://m1concourse.com/" target="_blank" rel="noopener noreferrer">Explore M1 Concourse &amp; upcoming events ↗</a></div></div><div><a href="https://m1concourse.com/" target="_blank" rel="noopener noreferrer"><img src="assets/m1-concourse.png" alt="M1 Concourse website"></a><p class="photo-credit" style="color:#44515d">M1 Concourse</p></div></section>'''
write('index','Home',home)

orgs=[]
def org(title,text,audience,urls,img=None,caption='',kind='',note='',extra=''):
 photo=f'<figure class="{kind}"><img src="assets/{img}" alt="{esc(caption,quote=True)}" loading="lazy"><figcaption>{caption}</figcaption></figure>' if img else ''
 return '<article class="card org">'+photo+f'<div class="card-body"><h3>{title}</h3><p>{text}</p><p class="audience"><strong>Useful for</strong>{audience}</p>'+ (f'<p class="personal">{note}</p>' if note else '')+extra+links(urls)+'</div></article>'
orgs.append('''<article class="card org org-feature"><div class="media-stack"><img class="logo-img" src="assets/wimna-logo.png" alt="Women in Motorsports North America logo"><img src="assets/wimna-car.png" alt="Spire Motorsports No. 7 car driven by Daniel Suárez at the 2026 Kansas fall race, featuring the WIMNA logo and all WIMNA members’ names" loading="lazy"><p class="photo-credit">Spire Motorsports’ No. 7 car, driven by Daniel Suárez at the 2026 Kansas fall race, featuring the WIMNA logo and all WIMNA members’ names.</p></div><div class="card-body"><span class="pill">Community &amp; career development</span><h3>Women in Motorsports North America</h3><p>WIMNA connects people across motorsports through networking, educational events, mentorship, and professional development. Women with Drive is its annual summit for learning, meeting people in the industry, and exploring careers throughout racing.</p><p class="audience"><strong>Useful for</strong>Students and early-career professionals interested in technical, business, and operational roles.</p><p class="personal">I competed in the first annual Women with Drive case competition.</p>'''+links([('Visit WIMNA','https://wimna.org/'),('Women with Drive Summit','https://www.womenwithdrivesummit.com/')])+'</div></article>')
orgs.append(org('Collegiate Racing Series','CRS creates opportunities for college students to take part in wheel-to-wheel racing and sim racing. A collegiate program can involve much more than driving: race preparation, team operations, data, sponsorship, and communications all matter.','College students interested in running and supporting a race team.',[('Collegiate Racing Series','https://drivecrs.com/'),('Programs & involvement','https://drivecrs.com/about/')],'collegiate-racing-series.png','Collegiate Racing Series — 2026 race schedule.','poster'))
orgs.append(org('Purdue Collegiate EV Grand Prix','College teams build, develop, and race electric karts while combining engineering with driving, data analysis, strategy, and team operations. The collegiate competition also includes design and energy-efficiency work.','College students across technical and team-support roles.',[('Collegiate EV Grand Prix','https://www.purdueevgrandprix.com/'),('Purdue program information','https://engineering.purdue.edu/evGrandPrix')],'ev-grand-prix.png','Lady Elizabeth EV’s purple No. 03 kart at Purdue.'))
orgs.append(org('High School EV Grand Prix','High-school teams build and race electric karts through a school-supported program. Students develop practical STEM and teamwork skills alongside a STEM report, outreach work, and test-and-tune events.','High-school students, teachers, and school teams.',[('High School EV Grand Prix','https://engineering.purdue.edu/evGrandPrix'),('Start a high-school team','https://engineering.purdue.edu/evGrandPrix/highschool/getting-started')],'high-school-ev-grand-prix.png','High School EV Grand Prix at Purdue.','uncropped'))
orgs.append(org('Formula SAE — Combustion','University teams design, manufacture, test, and compete with a small formula-style race car. Students practice mechanical design, vehicle dynamics, testing, cost analysis, and project management while learning how their decisions work on a real vehicle.','Students who want hands-on design, manufacturing, testing, or team-management experience.',[('Formula SAE','https://www.fsaeonline.com/')],'formula-sae.png','UConn’s No. 127 Formula SAE car.'))
orgs.append(org('Baja SAE','Students design and build an off-road vehicle, then test it through competition. The work emphasizes durability, suspension, fabrication, manufacturing, troubleshooting, and teamwork in demanding conditions.','Students interested in off-road vehicles, mechanical design, fabrication, and testing.',[('Baja SAE','https://www.bajasae.net/')],'baja-sae.png','Baja SAE off-road vehicle No. 37.'))
orgs.append(org('Formula SAE Electric','Electric Formula SAE teams integrate the mechanical vehicle with an electric powertrain, controls, and high-voltage systems. Vehicle dynamics, packaging, data, reliability, manufacturing, and safe testing remain central to the project.','Students interested in electric vehicles and the full range of technical and operational team roles.',[('Formula SAE Electric information','https://www.fsaeonline.com/')],'formula-sae-electric.png','RIT’s No. 204 Formula SAE Electric car.'))
orgs.append(org('Collegiate Solar Racing','Solar racing teams develop efficient vehicles for events such as the American Solar Challenge and Formula Sun Grand Prix. Students work across aerodynamics, structures, electrical systems, energy management, data analysis, and race operations.','Students interested in vehicle development, efficiency, systems engineering, and endurance competition.',[('American Solar Challenge','https://www.americansolarchallenge.org/')],'solar-racing.png','Missouri S&T’s No. 42 solar car.'))
orgs.append(org('eNASCAR College iRacing Series','A collegiate sim-racing series that lets eligible students represent their schools in organized competition. It is a way to practice race preparation, driving, telemetry review, and communication without operating a physical race car.','College students interested in competitive simulation and driver-performance analysis.',[('eNASCAR College series information','https://www.iracing.com/2026-27-enascar-college-iracing-series-tracks-format-unveiled-imsa-included-with-two-new-tournaments/')],'enascar-college.png','Sim-racing imagery from collegiate competition; this is a virtual race.'))
orgs.append(org('NABME','The National Advisory Board for Motorsports Education was jointly established by IMSA and Collegiate Racing Series to strengthen connections between higher education and the motorsports industry. It is an education and industry initiative, not a racing championship.','Students and educators following motorsports education pathways.',[('Read the IMSA announcement','https://www.imsa.com/news/2026/08/27/imsa-collegiate-racing-series-jointly-establish-national-advisory-board-for-motorsports-education/')],'nabme.png','National Advisory Board for Motorsports Education, powered by IMSA.','logo',extra='<div class="note"><strong>Newly established — August 2026</strong>NABME was founded in August 2026. More details on its initiatives and plans are expected as the board develops its programs; follow the official IMSA and CRS announcements for updates.</div>'))
orgs.append(org('Collegiate iRacing League','CIL organizes collegiate sim-racing competition across multiple series. Students can practice driving, telemetry analysis, race preparation, and team communication. It is separate from the eNASCAR College iRacing Series.','College students who want to compete or build analysis skills using simulation.',[('Collegiate iRacing League','https://www.collegiateiracingleague.com/'),('Series & formats','https://www.collegiateiracingleague.com/our-series')],'collegiate-iracing.png','Collegiate iRacing imagery: sports cars, stock cars, and open-wheel simulation.'))
orgs.append(org('National Association of Intercollegiate Racing','NAIR connects college students with motorsports education and organized intercollegiate sim racing. Its program brings technical learning together with business, marketing, and leadership experience.','College and university students interested in motorsports education and team participation.',[('About NAIR','https://nairacing.com/about/'),('NAIR events','https://nairacing.com/events/')],'nair-logo.png','National Association of Intercollegiate Racing.','logo'))
orgs.append(org('Sports Car Club of America — SCCA','SCCA offers ways to take part in autocross, track events, time trials, road racing, and event operations. Regional clubs are a practical starting point for meeting local racers, learning how events run, and finding a discipline that fits your interests.','Students and enthusiasts interested in grassroots competition, driving, and volunteering.',[('SCCA','https://www.scca.com/'),('Find your activity','https://www.scca.com/pages/find-your-fun')],'scca.png','SCCA sports car racing.'))
orgs.append(org('National Auto Sport Association — NASA','NASA organizes High Performance Driving Events (HPDE), time trials, and road racing through regional programs. HPDE provides structured driving instruction, while time trials and racing offer further routes into competition.','Drivers and students interested in track experience, car preparation, and regional racing.',[('NASA','https://drivenasa.com/'),('HPDE information','https://drivenasa.com/hpde')],'nasa.jpg','NASA endurance racing in Utah.'))
write('organizations','Organizations',head('Find your team','Organizations & student racing','Places to gain experience, meet people, and put your skills to work. Start with the program that fits your school, location, and interests.')+grid(orgs))

experience=head('Start where you are','Get hands-on experience','You do not need a professional race-team internship before you can begin. Local racing, karting, student competitions, volunteering, and personal projects can all build useful experience.')
experience+=section('01','Start as a fan',grid([
card('Go to a race','Attend a local karting or short-track event, or experience an IMSA, IndyCar, Formula 1, or NASCAR race. Watch how a weekend runs, learn the formats, and pay attention to preparation, pit stops, teamwork, and communication. You can start learning without driving or joining a team.'),
card('Find a club or watch party','Join a campus motorsports club or organize a race watch party to meet students with similar interests. Watching together is a low-pressure way to ask questions, compare observations, and find people for a karting trip, race visit, or student project.')]))
experience+=section('02','Ways to get involved',grid([
card('Owner karting','Run, maintain, and set up a kart that you or your team owns. It gives you repeated practice with alignment, tire pressures, gearing, preparation, data, and driver feedback. Helping an existing owner or team is a useful first step before buying equipment.'),
card('Volunteer with a kart or local team','Individual kart owners, karting teams, and local racing teams may need a mechanic, data analyst, or pit-crew member. Contact teams before the event, explain what you can do, and offer reliable shop or race-day help.'),
card('Student race teams','Join a university team, school EV kart team, or motorsports club. Ask about design, build, testing, logistics, budgeting, and communications roles; you do not have to be the driver.',[('Explore organizations','https://www.fsaeonline.com/')]),
card('Internships','Look beyond race engineering: manufacturing, suppliers, simulation, electronics, PR, partnerships, finance, HR, and operations can all provide relevant experience. Show completed work and explain what you learned.'),
card('Rental karting','Practice driving without owning or maintaining a kart. Focus on consistent laps, racing lines, braking, and useful driver feedback. Local leagues can provide regular competition, though setup changes and data access depend on the venue.'),
card('Sim racing','Use repeatable practice and telemetry to study driving, compare laps, and prepare for competition. Collegiate leagues offer ways to race with other students. Simulation can build analysis and communication skills, but it does not replace real-world vehicle testing.'),
card('Local short tracks & ARCA','Look up local teams and ask about preparation, shop work, timing, equipment, or data support. ARCA and short-track teams differ in staffing and resources; useful help starts with understanding what a particular team needs.',[('ARCA','https://www.arcaracing.com/')]),
card('24 Hours of Lemons','Endurance racing involves preparation, mechanical reliability, communication, and team logistics. Ask an existing team about helping with the build or race weekend, and read the rules before committing.',[('24 Hours of Lemons','https://24hoursoflemons.com/')]),
card('Track days, autocross & event support','Use organized driving events to practice observation, data review, and setup documentation. Events may also need timing, scoring, registration, media, or marshal support, subject to their training and access rules.',[('SCCA — getting started','https://www.scca.com/')])]))
experience+=section('03','What you can offer',grid([
card('Mechanic / shop helper','Help with cleaning, preparation, inspections, and maintenance under the team’s supervision. Be honest about your experience and learn its procedures.'),card('Data analyst','Organize timing and telemetry, compare laps, record setup changes, and turn driver feedback into useful questions. A short, readable report is often more useful than a complicated dashboard.'),card('Pit crew / race-day support','Help prepare tires and equipment, organize tools, track timing, and support communication or service allowed by the series. Training and credentials may be required.'),card('Business, media & operations','Build a budget, organize travel and inventory, write a sponsor update, take useful photos, or help with social media. These responsibilities are part of running a racing team.')]))
experience+='<div class="note"><strong>Start with a conversation.</strong>Visit a local kart club or race, meet owners and independent drivers, and ask what help they need. Learn the local classes and support options before buying a kart. Opportunities are by arrangement; volunteering does not guarantee unrestricted pit access.</div>'
rows=[('Owner karting','Equipment, entries, tires, repairs & transport','Setup, mechanics, data & driving','Track, budget & class dependent'),('Rental karting','Per-session fees','Driver consistency & feedback','Local venue dependent'),('Kart / local-team volunteering','Usually travel, time & equipment','Mechanics, data or race operations','Contact owners and teams'),('Student race team','Dues, travel & project costs vary','Design, build, testing & operations','School and team dependent'),('Sim racing','Hardware & software costs vary','Driving, telemetry & preparation','Suitable computer and service access'),('Internships','Application and relocation costs vary','Role-specific professional work','Eligibility, openings & schedule'),('Lemons team','Shared build and event costs','Preparation, reliability & teamwork','Team arrangement and rules')]
experience+=section('04','Compare your starting points','<div class="table-wrap opportunities"><table><thead><tr><th>Opportunity</th><th>Cost considerations</th><th>Experience</th><th>Accessibility</th></tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td data-label="{l}">{esc(v)}</td>' for l,v in zip(['Opportunity','Cost','Experience','Accessibility'],r))+'</tr>' for r in rows)+'</tbody></table></div>')
write('experience','Get Experience',experience)

skills={
'Design & development':[
('CAD','Create parts and assemblies and check packaging before manufacturing.'),('Mechanical design','Choose geometry, materials, fasteners, and load paths that fit the job.'),('GD&T','Use geometric dimensioning and tolerancing to communicate how a part must fit and function.'),('Manufacturing','Understand machining, forming, welding, and other production processes.'),('Composites','Consider fiber direction, layup, bonding, curing, and inspection.'),('FEA','Use finite element analysis to study stress and deflection, with realistic loads and constraints.'),('CFD','Use computational fluid dynamics to investigate airflow and cooling, then compare with testing.'),('Metrology','Measure parts and assemblies and quantify whether they meet requirements.'),('Quality','Track inspection results, process variation, and the causes of defects.'),('3D scanning','Capture surface geometry for inspection, packaging, or comparison.'),('Reverse engineering','Understand an existing component through measurements and its function.'),('Design reviews','Explain assumptions and tradeoffs before committing to a design.')],
'Data & software':[
('Excel','Build setup sheets, calculations, comparisons, and quick plots.'),('Python','Clean data, automate repetitive tasks, and build analysis tools.'),('MATLAB','Analyze signals, develop models, and run numerical studies.'),('Data visualization','Make plots that communicate a question and a usable conclusion.'),('Databases & SQL','Store organized data and retrieve consistent comparisons.'),('Data structures','Arrange data so it can be processed reliably and efficiently.'),('Telemetry analysis','Connect measured channels to driver inputs and vehicle behavior.'),('Automation','Make repeatable workflows with clear checks and failure messages.'),('AI & machine learning','Use appropriate models and assistants while checking inputs, leakage, and results.'),('Git / GitHub','Track changes, collaborate, and keep recoverable versions of your work.'),('Technical notes','Record channel definitions, units, assumptions, and decisions.')],
'Simulation':[
('Lap-time simulation (LTS)','Estimate performance around a circuit and compare design or setup changes.'),('Vehicle modeling','Represent how the vehicle responds to forces, inputs, and conditions.'),('Tire modeling','Describe tire forces as load, slip, camber, and operating conditions change.'),('Driver-in-the-loop (DIL)','Evaluate behavior with a human driver operating a simulator.'),('Static / quasi-static simulation','Study equilibrium states and steady operating conditions.'),('Offline simulation','Run a modeled maneuver or lap without a live driver.'),('Design of experiments (DOE)','Choose a useful set of tests to separate the influence of different inputs.'),('Correlation','Compare predictions with measured results and investigate disagreement.'),('Sensitivity studies','Change one input or a controlled set of inputs to see what matters most.')],
'Trackside & testing':[
('Sensors & instrumentation','Choose sensors, mounting, wiring, ranges, and sampling rates.'),('Data acquisition (DAQ)','Collect synchronized, usable measurements from the vehicle.'),('Sensor calibration','Convert raw outputs into physical values and check zero, scale, and drift.'),('Vehicle setup','Measure and document alignment, ride heights, corner weights, and settings.'),('Test planning','Define the question, procedure, conditions, and success criteria before running.'),('Troubleshooting','Use evidence to isolate electrical, mechanical, or data problems.'),('Driver feedback','Ask clear questions and connect observations to specific corners and phases.'),('Race communication','Give concise, timely information and confirm important changes.'),('Test documentation','Keep run sheets, conditions, changes, and conclusions together.')],
'Professional skills':[
('Communication','Explain the conclusion and why it matters to the person using it.'),('Problem solving','Define the problem, test assumptions, and work from evidence.'),('Technical writing','Make a report understandable and repeatable by someone else.'),('Presentation','Show the key result and answer questions without hiding uncertainty.'),('Project management','Plan time, budget, dependencies, and deliverables.'),('Team leadership','Set clear responsibilities, listen, and help people work together.'),('Working under pressure','Prioritize the decision that matters now and use consistent procedures.'),('Engineering judgment','Turn data and experience into a decision while recognizing limitations.')]
}
s=head('Build useful skills','Skills used in motorsports','Different jobs use different combinations of skills. Start with the fundamentals for the work you want to do, then develop them through a project or team.')
for i,(title,items) in enumerate(skills.items(),1):s+=section(f'{i:02}',title,'<ul class="skill-list">'+''.join(f'<li><strong>{esc(t)}</strong>{esc(d)}</li>' for t,d in items)+'</ul>')
write('skills','Skills',s)

roles={
'Engineering · Development':[
('Aerodynamics Engineer','Develops aerodynamic performance through CFD, wind-tunnel testing, aero maps, geometry changes, and correlation.'),('Design Engineer','Designs components and assemblies around loads, packaging, manufacturing, reliability, and serviceability.'),('Metrology Engineer','Measures components and assemblies with tools such as CMMs and 3D scanners to verify geometry and tolerances.'),('R&D Engineer','Develops and validates new parts, materials, test rigs, methods, and performance concepts.'),('Manufacturing Engineer','Develops reliable processes for making and inspecting components.')],
'Engineering · Competition':[
('Data Engineer / Data Analyst','Processes telemetry and helps the engineers and driver understand what happened on track.'),('Engine / Powertrain Engineer','Supports performance, reliability, calibration, and analysis of the engine or powertrain.'),('Vehicle Dynamics & Simulation Engineer','Studies how tires, suspension, aero, loading, setup, and driver inputs affect the car. Builds and uses vehicle, tire, lap-time, and driver-in-the-loop models to compare setups, predict behavior, and correlate results with track data.'),('Tire Engineer','Studies pressure, temperature, wear, degradation, construction, and tire performance.'),('Systems Engineer','Supports electronics, sensors, data acquisition, communications, and applicable controls.'),('Performance Engineer','Combines telemetry, simulation, driver feedback, setup analysis, and performance tools.'),('Race Engineer','Works with the driver and engineering team to set up the car and make performance decisions during an event.')],
'Race operations':[
('Crew Chief','Leads the team’s technical and race decisions; authority and responsibilities depend on the series.'),('Car Chief','Coordinates the preparation, assembly, legality, and readiness of a particular car.'),('Team Manager / Operations','Organizes people, schedules, budgets, credentials, logistics, and event execution.'),('Pit Crew','Performs practiced race-service tasks such as tire changes, fueling where permitted, and adjustments.'),('Spotter','Communicates traffic, incidents, track conditions, and relevant observations to the driver.'),('Tire Specialist','Prepares, measures, tracks, and manages tires and their usage history.')],
'Shop, fabrication & logistics':[
('Mechanic / Race Technician','Builds, services, inspects, and troubleshoots the car before and during events.'),('Machinist / CNC Programmer','Makes precision components and fixtures, selecting machining strategies and checking dimensions.'),('Fabricator / Welder','Builds and repairs structures, brackets, tubing, and other fabricated components.'),('Composite Technician','Lays up, cures, bonds, repairs, and inspects carbon-fiber or other composite parts.'),('Engine / Gearbox Builder','Assembles and inspects powertrain components to documented specifications.'),('Truck Driver / Transporter Operator','Transports cars and equipment and often helps manage the transporter and paddock setup.'),('Parts & Inventory Coordinator','Tracks components, spares, consumables, service history, and purchasing needs.')],
'Business, communications & people':[
('Public Relations','Handles media relationships, interviews, announcements, and team communications.'),('Marketing','Plans campaigns and content that connect the team with its audience and partners.'),('Sponsorships / Partnerships','Finds partners, develops proposals, manages relationships, and delivers agreed benefits.'),('Accountant / Finance','Manages budgets, reporting, payments, payroll coordination, and financial planning.'),('Human Resources','Supports recruiting, onboarding, employee relations, benefits, and people processes.'),('IT / Technology Support','Keeps team computers, networks, accounts, storage, and communications working reliably at the shop and track. Supports troubleshooting, backups, cybersecurity, and the systems engineers use to share data.'),('Social Media / Content','Creates and publishes useful event, team, driver, and partner content.'),('Photographer / Videographer','Documents events and produces imagery for media, team, and sponsor use.'),('Graphic Designer','Creates visual materials for communications, presentations, merchandise, and liveries.'),('Hospitality / Guest Experience','Organizes sponsor and guest visits, event spaces, schedules, and service.'),('Sales / Merchandise','Manages retail products, customer service, and commercial opportunities.')]
}
c=head('Find your role','Careers in motorsports','Race teams need much more than engineers. Explore the work behind the car, from design and data to fabrication, logistics, partnerships, and people.')
c+='<p class="note">Job titles vary significantly between teams and series. A responsibility handled by a dedicated specialist on one team may be part of a broader role on another.</p>'
for i,(title,items) in enumerate(roles.items(),1):c+=section(f'{i:02}',title,'<div class="role-list">'+''.join(f'<article class="role-item"><h3>{esc(t)}</h3><p>{esc(d)}</p></article>' for t,d in items)+'</div>')
c+=section('06','Building a path into the industry','<ol class="path">'+''.join(f'<li>{t}</li>' for t in ['Build foundational technical or business skills.','Join a student racing or hands-on organization.','Learn basic data analysis and telemetry.','Complete small motorsports-related projects.','Document your work and what you learned.','Attend events and meet people working in racing.','Apply for internships and realistic volunteer opportunities.','Keep developing communication and teamwork.'])+'</ol>','There is no single required route. Universities, trades, manufacturing, local racing, internships, and student teams can all lead to useful experience.')
write('careers','Careers',c)

projects=[
('Tire degradation tool','Use a run of lap times to estimate pace falloff. Separate out-laps, traffic, cautions, and changing fuel load before fitting a simple trend.','A plot, a short explanation of your exclusions, and a comparison of two runs.','Excel · Python · Data analysis','Beginner'),
('Driver pace comparison','Compare lap time, sectors, braking points, throttle application, and minimum speeds for two drivers or two laps. Align data by distance and check track conditions.','An annotated lap overlay and three specific areas to review.','Telemetry · Excel · MATLAB / Python','Beginner'),
('Kart balance notebook','Record setup, conditions, driver comments, and lap-time response. Describe understeer or oversteer by corner and phase rather than using only “tight” or “loose.”','A run sheet and a short conclusion about one controlled setup change.','Vehicle dynamics · Testing · Documentation','Beginner'),
('Multi-sensor data logger & CAN bench','Build a bench-top logger that synchronizes two or three sensors and reads messages from a CAN simulator or spare test device. Decode signals, calibrate measurements, detect missing samples, and compare the recorded signals with reference values. Start on a bench before considering vehicle installation.','A working logger, wiring diagram, signal definitions, and a short validation report.','Embedded programming · CAN · Instrumentation · Validation','Intermediate — stretch project'),
('Tire temperature study','Record temperatures across the tread after comparable runs. Keep the measurement order and timing consistent, and note that surface temperature changes quickly.','A measurement sheet and a plot comparing runs.','Testing · Data collection · Excel','Beginner'),
('Design, build & test a sensor bracket','Design a small kart sensor or data-logger bracket in CAD. Define its loads and clearances, choose a material and manufacturing process, and compare a simple hand calculation or FEA prediction with measured deflection on a bench prototype. Revise the design using the test result.','CAD and drawings, a prototype, a basic load test, and a comparison of predicted versus measured behavior.','CAD · Manufacturing · FEA · Physical testing','Intermediate — stretch project'),
('Track map generator','Plot GPS or simulation coordinates, then color the path by speed or another channel. Check coordinate units and remove obvious bad points.','A readable track map with a legend and labeled units.','Python · GPS · Visualization','Beginner'),
('Setup & inventory workbook','Create a simple setup log with conditions, driver feedback, and tire history. Add an inventory sheet so a team can track spare parts and consumables.','A reusable workbook with clear inputs and a completed example.','Excel · Operations · Documentation','Beginner'),
('Race strategy calculator','Estimate fuel and pit windows using a small set of inputs. Compare a few scenarios and show how the answer changes with fuel use, pit loss, or tire falloff.','A transparent spreadsheet or script with stated assumptions.','Excel · Python · Decision-making','Intermediate'),
('Sensor calibration project','Choose a temperature, position, or pressure sensor and compare it with a known reference across a useful range. Record repeatability as well as the best-fit calibration.','A calibration curve, units, and an error estimate.','Instrumentation · DAQ · Testing','Beginner'),
('Simple aero experiment','Use a model and tuft testing, or a basic CFD study, to investigate one clear airflow question. Change one feature at a time and explain the limits of your setup.','Before-and-after observations with a controlled procedure.','Aerodynamics · Design of experiments · Testing','Beginner–intermediate'),
('Race-weekend report & sponsor update','Turn public or simulated race data into a short report. Include results, a useful pace comparison, a simple budget or logistics lesson, and a concise sponsor-facing summary.','An engineering summary plus a one-page communications update.','Analysis · Writing · Marketing · Budgeting','Beginner')]
p=head('Learn by doing','Projects you can build','Start small and finish something you can explain. Most of these projects are beginner-friendly; two stretch projects add hands-on electronics, design, and validation when you are ready for more.')
p+=grid([f'<article class="card"><p class="project-number">PROJECT {i:02}</p><h3>{t}</h3><p>{d}</p><div class="project-meta"><strong>What to make</strong>{out}</div><div class="project-meta"><strong>Skills</strong>{sk}<br><span class="muted">{level}</span></div></article>' for i,(t,d,out,sk,level) in enumerate(projects,1)])
write('projects','Projects',p)

r=head('Keep learning','Technical resources','A starting set of tools, documentation, and learning material. Learn enough to complete a useful task, then build depth as you need it.')
r+='<article class="card resource-feature cream"><p class="eyebrow" style="color:#723e4e">Recordings, lectures & slides</p><h2>Vehicle dynamics seminar & course materials</h2><p>This Google Drive folder includes recordings from a Vehicle Dynamics seminar at MIA School of Race Engineering, plus lectures and slides from ME 54255, a graduate-level racecar vehicle dynamics course at Purdue.</p>'+links([('Open recordings, lectures & slides','https://drive.google.com/drive/folders/10Iy0Ycy1hV00RteSvgVl-vmbamHn3wUH?usp=sharing')])+'</article>'
r+=section('01','Vehicle dynamics & telemetry',grid([
card('OptimumG','Vehicle-dynamics education and technical articles, with student resources for learning modeling, setup, and vehicle performance.',[('OptimumG','https://optimumg.com/'),('Student resources','https://students.optimumg.com/'),('Technical papers','https://optimumg.com/technical-papers/')]),
card('Pi Toolbox','Cosworth’s motorsports data-analysis software for reviewing recorded data, comparing runs, and investigating vehicle and driver performance. Use the official product page for current downloads, documentation, and licensing.',[('Pi Toolbox — Cosworth','https://www.cosworth.com/motorsport/products/pi-toolbox/')]),
card('MoTeC i2','Motorsports data analysis for reviewing channels, comparing laps, building math channels, and connecting driver inputs to vehicle behavior.',[('MoTeC software & documentation','https://www.motec.com.au/')]),
card('AiM RaceStudio 3','Tools for configuring supported AiM devices and working with recorded data. Use the official downloads and documentation for your device and software version.',[('AiM downloads & documentation','https://www.aim-sportline.com/us/sw-fw-download.htm')]),
card('Penske Racing Shocks','Manufacturer manuals and tuning material for understanding dampers, adjustments, and force-versus-shaft-velocity behavior.',[('Penske technical downloads','https://www.penskeshocks.com/resources/downloads')])]))
r+=section('02','Python — start here',grid([
card('Intro to programming','A gentle first step if you have never programmed. Practice variables, functions, and basic logic before moving to racing datasets.',[('Kaggle: Intro to Programming','https://www.kaggle.com/learn/intro-to-programming/course')]),
card('Python fundamentals','Practice Python syntax, collections, loops, and functions through short exercises.',[('Kaggle: Python','https://www.kaggle.com/learn/python')]),
card('Official Python tutorial','A reference and guided introduction for people who already understand basic programming concepts.',[('Python tutorial','https://docs.python.org/3/tutorial/index.html')]),
card('pandas — work with tables','Learn to read CSV files, select data, calculate columns, and group results. These are useful starting skills for lap-time and telemetry analysis.',[('pandas introductory tutorials','https://pandas.pydata.org/docs/getting_started/intro_tutorials/')]),
card('Matplotlib — make useful plots','Build line plots, scatterplots, subplots, and clear labels. Start by plotting one channel against time or distance.',[('Matplotlib tutorials','https://matplotlib.org/stable/tutorials/index.html')])]))
r+=section('03','Engineering & project tools',grid([
card('MATLAB & Simulink','Numerical analysis, signal processing, modeling, simulation, and automation. Start with small scripts and check units and inputs.',[('MathWorks learning','https://matlabacademy.mathworks.com/')]),
card('Excel','Useful for setup sheets, budgets, quick calculations, strategy comparisons, and dashboards. Keep input cells and assumptions easy to find.',[('Excel help & learning','https://support.microsoft.com/excel')]),
card('CAD','Learn part design, assemblies, drawings, and manufacturing considerations. Build a simple bracket or fixture and explain its load path.',[('Autodesk learning','https://www.autodesk.com/learn')]),
card('FEA & CFD','Use structural and flow simulation to investigate specific questions. Boundary conditions, mesh quality, and correlation matter more than attractive contours.',[('Ansys learning resources','https://courses.ansys.com/')]),
card('Git / GitHub','Version control helps you track changes, collaborate, recover earlier work, and document a project clearly.',[('GitHub Skills','https://skills.github.com/'),('Git documentation','https://git-scm.com/doc')]),
card('Arduino & electronics','A practical route into basic sensor, instrumentation, and data-logging projects. Start with safe bench-top measurements.',[('Arduino documentation','https://docs.arduino.cc/')])]))
r+=section('04','More technical learning',grid([
card('Racetrack Dynamics','Motorsport engineering courses covering subjects such as vehicle dynamics and aerodynamics. Explore the course outlines to find a topic that fits your experience.',[('Racetrack Dynamics','https://racetrackdynamics.com/')]),
card('Racecar Engineering — Tech Explained','Technical articles explaining race-car systems, engineering concepts, and design choices across motorsport.',[('Read Tech Explained','https://www.racecar-engineering.com/category/tech-explained/')]),
card('CAN & CAN FD data acquisition','Dewesoft’s online course introduces CAN and CAN FD communication and how to acquire and work with bus data. Useful background for instrumentation and logging projects.',[('Dewesoft CAN course','https://dewesoft.com/academy/online/can-bus-can-fd-data-acquisition')]),
card('RacePhysiX','A vehicle-dynamics and lap-time simulator for exploring how model inputs influence predicted behavior. Use its documentation to understand the assumptions behind the results.',[('RacePhysiX','https://racephysix.com/')]),
card('Racing Car Dynamics','Technical articles on race-car behavior and engineering, useful for working through vehicle-dynamics concepts alongside textbooks and practical testing.',[('Racing Car Dynamics','https://racingcardynamics.com/')])]))
r+=section('05','Careers & the motorsport industry',grid([
card('Find motorsports jobs','Explore engineering, technical, operational, business, and support roles. Compare job descriptions to identify skills you can develop through your next project or team experience.',[('Racer Jobs','https://www.racerjobs.com/'),('Motorsport Jobs','https://www.motorsportjobs.com/en')]),
card('Motor Racing Industry','A directory of teams, manufacturers, suppliers, and specialist services. Useful for discovering the range of businesses behind racing and researching potential employers.',[('Motor Racing Industry','https://www.motorracingindustry.com/')])]))
write('resources','Resources',r)

book_links={1:('Book information','https://www.millikenresearch.com/rcvd.html'),5:('Milliken book catalog','https://www.millikenresearch.com/books.html'),9:('SAE book information','https://saemobilus.sae.org/books/generalized-vehicle-dynamics-r-498'),10:('Preview / book information','https://books.google.com/books/about/Racing_Car_Design_and_Development.html?id=Ba7iAAAACAAJ'),12:('Publisher information','https://www.evropublishing.com/products/the-perfect-car-the-story-of-john-barnard-motorsport-s-most-creative-designer'),13:('Book information','https://bookshop.org/p/books/basic-vehicle-dynamics-and-suspension-design-r-dale-white/19962532'),15:('Publisher information','https://www.routledge.com/Vibration-Control-of-Vehicle-Suspension-Systems/Du-Li-Ning/p/book/9781032208787'),21:('Preview / book information','https://books.google.com/books/about/Formula_One_Race_Engineering.html?id=rboN0QEACAAJ'),24:('Preview / book information','https://books.google.com/books?id=H46_swEACAAJ'),26:('Official free textbook resources','https://www.statlearning.com/')}
book_links={i+1 if i>=5 else i:v for i,v in book_links.items()}
book_links[5]=('Publisher information','https://link.springer.com/book/10.1007/978-3-031-06461-6')
b=head('The reading list','Books worth spending time with','This reading list was compiled primarily from recommendations from race engineers and technical directors I’ve worked with or interviewed, along with books from my own research and reading. If you’re only choosing a few, start with the first four.')
b+='<p class="section-intro">The first four are outlined as recommended starting points. After book 5, the order does not indicate importance.</p><div class="book-list">'
for i,line in enumerate(json.loads((ROOT/'tools/books.json').read_text()),1):
 full,cat,note=line.split(' | ',2);full=re.sub(r'^\d+ ','',full);title,author=full.split(' — ',1);note=note.replace('https://www.statlearning.com/','').strip();urls=[book_links[i]] if i in book_links else []
 b+=f'<article class="book {"recommended" if i<=4 else ""}"><span class="book-number">{i:02}</span><div>'+('<span class="start-here">Start here</span>' if i<=4 else '')+f'<h2>{esc(title)}</h2><p class="author">{esc(author)}</p><span class="pill">{esc(cat)}</span></div><div class="description"><p>{esc(note)}</p>'+links(urls)+'</div></article>'
b+='</div>';write('books','Books',b)

# The dynamics content is kept separate so technical edits can be made without redesigning other pages.
from dynamics import render_dynamics
write('vehicle-dynamics','Vehicle Dynamics',head('Understand the car','Introduction to vehicle dynamics','A first-order setup guide: connect common adjustments to what the driver feels, then test those ideas against data.')+render_dynamics())
print('Built nine static pages.')
