from html import escape as e
# Entries: adjustment, typical effect, where, why, opposite, conditions.
GROUPS=[
('aero','Aerodynamics',[
('More front aero','More front lateral capacity at speed; usually less high-speed understeer.','Fast corners','More aerodynamic load at the front shifts the available axle force balance.','Less front aero usually shifts balance toward high-speed understeer.','Tire load sensitivity, drag, and the complete aero map still matter.'),
('More rear aero','Usually more rear stability and less high-speed oversteer.','Fast corners and exit','Additional rear vertical load increases rear lateral capacity.','Less rear aero can reduce rear stability while reducing drag.','The balance shift matters as well as the total downforce.'),
('Aero balance forward / rearward','Forward generally adds high-speed rotation; rearward generally adds stability.','Fast corners','The front share of aerodynamic load changes relative to the rear.','Moving balance rearward reverses the usual tendency of moving it forward.','A balance change does not necessarily mean more total downforce.'),
('Lower front ride height / splitter','Can increase front or total downforce within the intended operating window.','High-speed running','Changes the pressure distribution around the nose and underfloor.','Raising the front changes ground interaction and may reduce load in that operating range.','Too low can cause bottoming, flow separation, choking, or abrupt aero changes. Use the aero map.'),
('Lower rear ride height','Changes floor and diffuser performance and aero balance.','High-speed running','Changes underfloor geometry, expansion, and pressure recovery.','Raising the rear moves the vehicle to a different aero-map operating point.','There is no universal understeer or oversteer direction.'),
('More rake','Changes downforce and aero balance.','Aero-platform control','Changes the inclination of the vehicle and underfloor relative to the track.','Less rake creates a flatter platform and a different aero operating point.','More rake does not always add front grip. Evaluate ride height, yaw, roll, and pitch together.'),
('More front wing angle','Usually more front load and drag before stall.','Fast corners and straights','Changes wing circulation and pressure difference.','Less angle generally reduces front load and drag.','Effects depend on geometry, interaction with the rest of the car, and flow separation.'),
('More rear wing angle','Usually more rear grip and stability, with more drag.','Fast corners and straights','Increases rear aerodynamic loading within the useful range.','Less angle usually reduces rear load and can improve straight-line speed.','Maximum speed also depends on power, gearing, and the rest of the aero package.'),
('Larger gurney / wicker','Can increase element loading and drag.','High-speed running','Changes the trailing-edge flow and pressure distribution.','A smaller gurney generally reduces its loading effect.','The location determines which axle gains load; gains are not unlimited.'),
('More effective diffuser','Can increase underfloor contribution to downforce.','High-speed running','A well-matched diffuser supports useful underbody flow and pressure recovery.','Reduced diffuser effectiveness can reduce underfloor load.','Handling follows the resulting aero balance. “More diffuser” does not automatically mean more rotation.'),
('Drag trim','Can improve straight-line speed while reducing aero grip.','Straights versus fast corners','Trades aerodynamic load for lower resistance.','More downforce generally brings greater drag and cornering potential.','Choose for the circuit, passing requirements, and vehicle power.')]),
('springs','Springs & anti-roll bars',[
('Stiffer front springs','More platform support; often an understeer tendency and less compliance.','Braking, roll, and sustained cornering','Raises front wheel/ride stiffness and can increase the front share of elastic lateral load transfer.','Softer front springs allow more movement and may improve mechanical grip on uneven surfaces.','Aero-platform benefits, geometry, travel, and bump-stop contact can outweigh the simple mechanical tendency.'),
('Stiffer rear springs','More rear platform support; often more rotation and less rear compliance.','Cornering and throttle transitions','Can increase the rear share of elastic lateral load transfer and reduce surface compliance.','Softer rear springs often improve rear compliance but allow more platform movement.','Evaluate the actual wheel rates and aero-platform response, not just the spring labels.'),
('Stiffer front anti-roll bar','Usually more understeer.','Lateral loading','Increases the front share of elastic lateral load transfer, which can reduce combined front-tire capability through load sensitivity.','A softer front bar usually reduces that front share and can improve front mechanical grip.','Camber control, suspension geometry, inside-wheel unloading, and aero can alter the outcome.'),
('Stiffer rear anti-roll bar','Usually more rotation or oversteer tendency.','Lateral loading','Increases the rear share of elastic lateral load transfer.','A softer rear bar usually adds rear grip or stability.','An unloaded inside driven tire can limit traction; differential behavior matters.'),
('Stiffer at both ends','Less movement and potentially better platform control, not automatically more grip.','Roll, pitch, and heave','Changes body-motion response and compliance; stiffness distribution determines much of the balance effect.','Softer overall settings increase movement and surface compliance.','Preserve adequate travel and evaluate tires, track roughness, and aero together.'),
('Earlier bump-stop / bump-spring engagement','Can sharply increase effective wheel rate and change balance.','Large displacement and aero loading','An additional spring element becomes active as suspension travel is used.','Later engagement preserves the initial rate over more travel.','Rate, gap, motion ratio, and which corners engage are all important.')]),
('dampers','Dampers',[
('More front low-speed compression','Resists front compression and changes pitch/platform response.','Brake application and turn-in','The damper produces more opposing force while the suspension compresses in the relevant velocity range.','Less compression damping allows faster compression and can improve compliance.','Too much can transmit disturbances into the chassis; do not assume a universal balance change.'),
('More rear low-speed compression','Resists rear compression and changes squat/roll response.','Throttle application and transitions','Opposes rear suspension compression while it is moving.','Less damping permits faster rear compression.','Traction and rotation depend on geometry, tires, and the transient being considered.'),
('More front low-speed rebound','Slows front extension and can keep the front lower for longer during a transition.','Brake release and acceleration transitions','Rebound force opposes suspension extension.','Less rebound allows faster extension.','It does not universally cause entry understeer; consider the complete maneuver.'),
('More rear low-speed rebound','Slows rear extension and changes transient rear loading.','Braking and roll transitions','Resists rear droop while the suspension extends.','Less rebound permits faster extension.','The handling direction depends on which tires are extending and the vehicle architecture.'),
('More high-speed compression','Greater resistance to rapid compression; potentially less bump compliance.','Curbs, sharp bumps, and impacts','Produces more force during rapid shaft movement.','Less high-speed compression can let the wheel absorb an impact more readily.','Too little can permit excess travel or bottoming; too much can reduce contact quality.'),
('More high-speed rebound','Slows wheel extension after a rapid compression event.','Recovery after bumps and curbs','Opposes rapid suspension extension.','Less rebound lets the wheel return more quickly but can allow oscillation.','Excessive rebound can prevent recovery between repeated bumps and contribute to packing.')]),
('alignment','Alignment & steering',[
('More front toe-out','Often sharper initial response, with more scrub and potentially less straight-line stability.','Initial turn-in and straight-line running','Changes the front tires’ initial directions and slip behavior.','More toe-in often favors straight-line stability with a different initial response.','Temperature, wear, compliance steer, and series conventions matter.'),
('More rear toe-in','Usually more rear stability and less willingness to rotate.','Corner entry and exit','Changes rear tire slip behavior and stabilizing response.','Less toe-in can free the rear; toe-out can be aggressive and destabilizing.','More toe also increases scrub and can add heat and drag.'),
('More negative front camber','Can increase lateral grip toward the tire’s preferred loaded camber.','Cornering','Helps the loaded tire operate at a favorable contact-patch orientation.','Less negative camber may improve the straight-line footprint but reduce cornering capability.','Beyond optimum it can reduce grip and increase inside-edge wear; braking is a tradeoff.'),
('More negative rear camber','Can increase rear lateral grip toward optimum.','Cornering versus acceleration','Changes the orientation and load distribution of the rear contact patch.','Less negative camber may support longitudinal traction at the cost of lateral performance.','Excessive camber can hurt drive and braking capability.'),
('More positive caster','Changes steering-induced camber, self-centering, steering effort, and jacking.','Steering and cornering','Alters the steering-axis geometry and wheel motion as steer angle changes.','Less caster reduces some of those geometric effects.','Do not equate more caster with a guaranteed gain in grip or driver feel.'),
('More Ackermann','Changes the inner-to-outer front steering-angle relationship.','Low-speed turns and loaded cornering','Inside and outside tires follow different radii and may require different slip angles.','Reduced or anti-Ackermann changes that relationship in the other direction.','Race-tire load and slip-angle requirements may favor reduced Ackermann; more is not always better.'),
('Faster steering ratio','More road-wheel angle for the same steering-wheel movement.','Driver inputs','Changes the conversion between steering-wheel and road-wheel angle.','A slower ratio requires more hand movement for the same wheel angle.','It does not inherently create more tire grip.')]),
('geometry','Track width, mass & geometry',[
('Wider front track','Often reduces front load transfer for a given front roll moment and may improve axle grip.','Lateral loading','A wider lateral lever arm can support the same roll moment with a smaller wheel-load difference.','Narrowing front track tends to increase that load difference, all else equal.','Geometry, roll stiffness, camber, and overall load-transfer distribution also change.'),
('Wider rear track','Can improve rear axle grip or stability under comparable conditions.','Lateral loading','Changes the lever arm that reacts rear roll moment.','A narrower rear track can increase load difference and change rotation.','Kart behavior is particularly coupled to jacking and inside-rear unloading; do not transfer car rules blindly.'),
('Wheel offset change','Changes track width and may change scrub radius and steering loads.','Steering, bearings, and suspension loading','Moves the contact patch relative to the steering axis and hub.','The reverse offset change moves those lever arms back the other way.','Specify the actual wheel/contact-patch position. “More offset” alone is an ambiguous handling instruction.'),
('Lower center of gravity','Generally reduces acceleration-driven lateral and longitudinal load transfer.','Braking, acceleration, and cornering','Reduces the moment arm between the center of gravity and the ground.','A higher CG increases those moments.','Ground clearance, geometry, and aero-platform limits still apply.'),
('Move weight forward','Increases front static load and often shifts steady-state balance toward understeer.','Steady cornering and braking','Changes axle loads, tire load sensitivity, and the force each axle must provide.','Moving weight rearward increases rear static load and may help rear-drive traction.','Brake balance, tires, wheelbase, and transient behavior matter; entry stability is not guaranteed.'),
('Centralize mass','Reduces yaw inertia and can make yaw response quicker.','Transient direction changes','Placing mass closer to the CG reduces its contribution to rotational inertia.','Moving mass farther from the CG increases yaw inertia.','Faster response is not automatically easier to drive.')]),
('oval','Oval setup: crossweight / wedge, rounds & stagger',[
('More RF/LR crossweight (wedge)','Often a tighter tendency or more on-throttle stability in a conventional left-turn oval setup.','Oval cornering and exit','Changes the diagonal distribution of static tire loads.','Less RF/LR crossweight often frees the car.','Highly dependent on banking, geometry, springs, stagger, track direction, and rear suspension.'),
('Rounds: spring-perch / jack-bolt adjustment','Changes corner loads, diagonal loads, and often ride height.','Static setup and platform','Changes spring installation or preload and the equilibrium of the connected vehicle.','Lowering it changes the equilibrium in the opposite adjustment direction.','A “round” is a hardware adjustment, not a fixed number of pounds. Verify on scales and with ride-height measurements.'),
('Change both front perches','Changes front ride height and can change rake and aero balance.','Static platform and high-speed running','Moves the vehicle’s operating point and may affect suspension travel.','The opposite change moves front platform height the other way.','Recheck all corner loads and ride heights rather than assuming they remain unchanged.'),
('Change both rear perches','Changes rear ride height, rake, and floor/diffuser operating point.','Static platform and high-speed running','Alters the rear platform and suspension operating position.','The opposite adjustment changes rear platform height in the other direction.','Use scales, measured heights, and the aero map together.'),
('More rear stagger','Can increase the natural turning tendency in the intended direction.','Oval and solid-axle kart applications','Different rolling circumferences influence the path the coupled rear wheels tend to follow.','Less stagger reduces that natural turning tendency.','Direction, tire growth, slip, loading, and differential architecture matter. Cold and hot stagger can differ.'),
('Geometric rear steer','Can change yaw response and cornering attitude.','Suspension movement and cornering','Rear-wheel direction changes the force direction and desired vehicle path.','Reversing the steer direction changes its influence on yaw.','“Toward the corner” is not a reliable universal rotation rule: coordinate convention, phase, and geometry must be specified.'),
('Aerodynamic skew / yaw','Changes downforce, sideforce, drag, and aero balance.','Speed and cornering attitude','Air meets the body and aero surfaces at a different yaw angle.','Opposite yaw or less skew produces another point on the aero map.','Do not assume more skew always makes the car loose.')]),
('brakes','Brakes',[
('More front brake bias','More front braking contribution and often better rear stability under braking.','Braking and entry','Moves a greater share of braking torque to the front axle.','More rear bias may add entry rotation but raises rear-lock risk.','Too much front bias can lock the fronts early and reduce maximum deceleration.'),
('More duct blanking / brake tape','Raises brake temperatures and may reduce cooling drag.','Repeated braking','Reduces cooling airflow through the brake system.','Opening ducts increases cooling and can lower component temperatures.','Too hot can cause fade, fluid overheating, wear, or thermal damage; too cold can also be outside the friction material’s window.'),
('Larger / heavier / thicker rotor','More thermal capacity and generally slower temperature rise for a given energy input.','High brake-energy conditions','More thermal mass can absorb more energy for a given temperature increase.','A smaller or lighter rotor reduces mass but has less thermal reserve.','Diameter also changes torque leverage. Added rotating and unsprung mass, packaging, and cooling are tradeoffs.'),
('More rotor ventilation','Can improve heat rejection and change the thermal response.','Sustained braking','Moves more cooling air through the disc when the ducting and rotation are suitable.','Less ventilation reduces cooling potential under comparable conditions.','Rotor design and duct routing matter; more airflow is not always the target.'),
('Iron versus carbon systems','Different friction behavior, thermal properties, and useful temperature ranges.','Series-specific braking conditions','Materials behave differently under heat, pressure, wear, and environmental conditions.','Changing material requires a compatible pad/disc system and operating approach.','Neither is universally superior. Follow the system manufacturer’s guidance.'),
('Higher-friction front / rear pad','Can shift effective braking-torque distribution toward the axle with the higher friction coefficient.','Braking','Pad friction contributes to brake torque along with clamp force and effective radius.','Lower friction on that axle can shift the effective distribution away from it.','Coefficient varies with temperature, pressure, and speed; do not treat compounds simply as “hard” or “soft.”'),
('More initial bite / flatter friction-temperature curve','Higher bite feels more immediate; a flatter curve can give more consistent response through temperature changes.','Brake application and changing thermal conditions','Pad compounds differ in friction, release, modulation, and temperature response.','Less bite may feel less aggressive; a changing friction curve can make response vary more.','Consider fade, pad wear, disc wear, and modulation as well as peak friction.')]),
('differential','Differential',[
('More power-side lock','More rear-wheel coupling under throttle; can add stability or power understeer.','Acceleration and exit','Resists speed difference between the driven wheels under power.','Less power lock permits more differentiation but may increase inside-wheel spin.','Architecture, tire loading, torque, and whether one or both tires saturate can change the handling direction.'),
('More coast-side lock','Often greater entry stability.','Off-throttle and braking phases','Increases wheel coupling in the coast operating condition.','Less coast lock often permits more entry rotation.','Effect depends on the differential, brake distribution, and tire loading.'),
('More preload','More resistance to differentiation around low-torque or transition conditions.','Neutral torque and power/coast transitions','Adds an initial resisting torque before some torque-sensitive mechanisms dominate.','Less preload allows freer differentiation near neutral conditions.','Terminology and adjustment response differ by differential architecture.')]),
('tires','Tire pressures',[
('Pressure below the useful window','Can cause excess carcass movement, poor support, heat, or sluggish response.','The full run','The tire is not adequately supported for its construction and load.','Raising pressure toward the target can improve response, footprint behavior, and grip.','Use the tire manufacturer’s limits and measured behavior; low pressure is not automatically more grip.'),
('Pressure above the useful window','Can reduce compliance and change the footprint unfavorably.','The full run','Higher pressure changes tire stiffness, deformation, and load distribution.','Reducing pressure toward the target may recover compliance and performance.','Pressure is not a monotonic grip adjustment: both too low and too high can be poor.'),
('Choose cold pressure for the hot target','A suitable starting pressure helps reach the desired operating window.','Warm-up and sustained running','Pressure changes as the tire heats and its gas temperature changes.','A different cold setting produces a different hot result only under comparable conditions.','Track temperature, loading, driving, brake heat, construction, starting temperature, and run length all affect growth.')])]

TERMS=[('Slip angle','The angle between the direction a tire points and the direction its contact patch travels.'),('Slip ratio','A measure of the difference between circumferential tire speed and road speed during driving or braking.'),('Tire load sensitivity','The tendency for tire force capacity to increase less than proportionally as vertical load increases.'),('Friction circle / ellipse','A simplified picture of how a tire shares its available force between braking, driving, and cornering.'),('Lateral load transfer','The change in left/right tire loads associated with cornering.'),('Longitudinal load transfer','The change in front/rear tire loads associated with braking or acceleration.'),('Roll center','A geometric reference used to describe suspension force transmission and body roll.'),('Roll couple','The rolling moment associated with lateral forces and their lever arms.'),('Wheel rate','The effective spring stiffness measured at the wheel.'),('Motion ratio','The relationship between wheel movement and spring or damper movement; always state the convention.'),('Ride rate','The effective vertical stiffness seen by the sprung mass, including relevant compliances such as the tire.'),('Natural frequency','The frequency at which a system tends to oscillate when disturbed.'),('Critical damping','The damping level separating oscillatory from non-oscillatory response in an ideal second-order system.'),('Aero balance','The front/rear distribution of aerodynamic load.'),('Center of pressure','The point through which the resultant aerodynamic force is represented as acting.'),('Understeer gradient','A measure of how required steering changes with lateral acceleration under specified steady-state conditions.'),('Differential locking','Resistance to a speed difference between the driven wheels.'),('Crossweight','The share of total static vehicle weight carried by a specified diagonal pair.'),('Stagger','The difference between outside and inside tire rolling circumferences.'),('Bump steer','A change in wheel steer angle as the suspension moves.'),('Anti-dive','Suspension geometry that reacts part of the braking pitch moment through suspension forces.'),('Anti-squat','Suspension geometry that reacts part of the acceleration pitch moment through suspension forces.')]

def render_dynamics():
 out='<div class="note"><strong>How to use this guide</strong>These are generalized first-order tendencies, not universal rules. Results depend on the vehicle, tire, track, aero map, geometry, driver inputs, and other setup parameters. Change one clearly defined thing, record conditions, and compare driver feedback with measurements.</div>'
 out+='<nav class="topic-nav" aria-label="Vehicle dynamics topics">'+''.join(f'<a href="#{id}">{title.split(":")[0]}</a>' for id,title,rows in GROUPS)+'</nav>'
 for id,title,rows in GROUPS:
  out+=f'<details id="{id}" class="dynamics-section"><summary><h2>{title}</h2><span class="expand-label" aria-hidden="true"></span></summary><div class="dynamics-body">'
  if id=='dampers':
   out+='''<p class="section-intro">Dampers primarily shape transient motion and the timing of load transfer. They do not simply change the total acceleration-driven load transfer.</p><div class="card cream"><h3>Damper shaft-velocity guide</h3><p>“Low speed” and “high speed” describe how fast the damper shaft moves, not how fast the car travels. The dividing point depends on the damper and its valving.</p><div class="role-list"><div class="role-item"><h4>Low shaft velocity</h4><p>Often associated with roll, pitch, heave, brake application/release, and steering transitions.</p></div><div class="role-item"><h4>High shaft velocity</h4><p>Often associated with curbs, sharp bumps, surface impacts, and sudden wheel movement.</p></div></div><p><strong>Compression:</strong> the damper shortens. <strong>Rebound:</strong> the damper extends. Adjuster ranges can overlap, so use the damper’s force–velocity curves and documentation.</p></div>'''
  if id=='oval':out+='<p class="section-intro">Oval / generalized. Conventions and direction of travel matter. <strong>Wedge</strong> commonly refers to crossweight or an adjustment to it. <strong>Rounds</strong> are turns of a spring perch or jack bolt used to change the setup. They can change wedge and ride height, but rounds and wedge are not the same measurement.</p><div class="equation">Crossweight % = (RF + LR) / total vehicle weight × 100<br>Stagger = outside tire circumference − inside tire circumference</div>'
  if id=='tires':out+='<p class="section-intro">Think in terms of an operating window, not “higher pressure = less grip.”</p>'
  for name,effect,where,why,opposite,conditions in rows:
   out+=f'<article class="adjustment"><h3>{e(name)}</h3><dl>'+''.join(f'<dt>{label}</dt><dd>{e(text)}</dd>' for label,text in [('Typical effect',effect),('Where it matters',where),('Why',why),('Opposite adjustment',opposite),('Conditions',conditions)])+'</dl></article>'
  out+='</div></details>'
 out+='<details class="dynamics-section"><summary><h2>Terms to learn next</h2><span class="expand-label" aria-hidden="true"></span></summary><div class="dynamics-body"><dl class="terms" style="margin-top:25px">'+''.join(f'<div><dt>{e(t)}</dt><dd>{e(d)}</dd></div>' for t,d in TERMS)+'</dl></div></details>'
 out+='''<aside class="source-links"><h3>Go deeper with technical references</h3><p class="muted">Use established texts and manufacturer documentation alongside this introductory guide.</p><ul><li><a href="https://www.millikenresearch.com/rcvd.html" target="_blank" rel="noopener noreferrer">Milliken &amp; Milliken — Race Car Vehicle Dynamics</a></li><li><a href="books.html">Carroll Smith — Tune to Win, and the full reading list</a></li><li><a href="https://optimumg.com/technical-papers/" target="_blank" rel="noopener noreferrer">OptimumG technical papers</a></li><li><a href="https://www.penskeshocks.com/resources/downloads" target="_blank" rel="noopener noreferrer">Penske Racing Shocks manuals and tuning guides</a></li><li><a href="https://apracing.com/race-car/brake-discs/disc-temperatures" target="_blank" rel="noopener noreferrer">AP Racing — disc temperatures</a></li><li><a href="https://apracing.com/race-car/brake-discs/disc-cooling" target="_blank" rel="noopener noreferrer">AP Racing — disc cooling</a></li></ul></aside>'''
 return out
